group 'com.sayegh.move_to_background'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'

android {
    namespace 'com.sayegh.move_to_background'
    compileSdk = flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    lint {
        disable 'InvalidPackage'
    }
}
